easternkite/brocallie

- androidApp/src/main/java/com/blucky8649/brocallie/android/MyApplicationTheme.kt
- androidApp/src/main/java/com/blucky8649/brocallie/android/ui/BcApp.kt
This update introduces dynamic theming, allowing the app to seamlessly adapt its color scheme to the user's system color palette settings. This creates a more personalized and visually harmonious experience for each user.
```kotlin
@Composable
fun MyApplicationTheme(
darkTheme: Boolean = isSystemInDarkTheme(),
//...
) {
val context = LocalContext.current
val colors = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
if (darkTheme) {
dynamicDarkColorScheme(context)
} else {
dynamicLightColorScheme(context)
}
} else {
MaterialTheme.colorScheme
}
//...
}
```
> Apply Dynamic Theme on Android

- shared/core/designsystem/src/commonMain/kotlin/com/blucky8649/designsystem/BcText.kt
- shared/core/designsystem/src/commonMain/kotlin/com/blucky8649/designsystem/BcTopAppBar.kt
- shared/feature/contactdetails/src/commonMain/kotlin/com/blucky8649/contactdetails/ContactDetailScreen.kt
- shared/feature/contacts/src/commonMain/kotlin/com/blucky8649/contacts/ContactItem.kt
- shared/feature/contacts/src/commonMain/kotlin/com/blucky8649/contacts/ContactsScreen.kt
* Dynamically adjust UI colors based on Material theme.
* Add BcText
> Update UI colors with Material theme

- androidApp/src/main/AndroidManifest.xml
- androidApp/src/main/res/values-ko-rKR/strings.xml
- androidApp/src/main/res/values/strings.xml
- gradle/libs.versions.toml
- iosApp/InfoPlist.xcstrings
- iosApp/iosApp.xcodeproj/project.pbxproj
- shared/core/designsystem/src/commonMain/kotlin/com/blucky8649/designsystem/BcTopAppBar.kt
- shared/feature/contactdetails/src/commonMain/kotlin/com/blucky8649/contactdetails/ContactDetailScreen.kt
Support multiple languages for app name
* Android : Use string.xml
* iOS : Use String Catalogs
> Support multiple languages for app name

- build-logic/convention/build.gradle.kts
- build-logic/convention/src/main/kotlin/BrocallieDesignSystemPlugin.kt
- gradle/libs.versions.toml
- shared/build.gradle.kts
- shared/feature/contactdetails/build.gradle.kts
- shared/feature/contacts/build.gradle.kts
Add convention plugin for design system
> Add convention plugin for design system

- build-logic/convention/src/main/kotlin/com/blucky8649/brocallie/ComposeMultiplatform.kt
- gradle/libs.versions.toml
- shared/feature/conversation/src/commonMain/kotlin/com/blucky8649/conversation/ChatCircleImage.kt
Add chat circle image and implement coil3
* implement coil3 version `3.0.0-alpha`
* add chatCircleImage
> Add chat circle image and implement coil3

- shared/core/generative-ai/src/commonMain/kotlin/com/blucky8649/generative_ai/Gemini.kt
- shared/feature/conversation/build.gradle.kts
- shared/feature/conversation/src/commonMain/kotlin/com/blucky8649/conversation/ChatViewModel.kt
> Add gemini in Chat

- build-logic/convention/src/main/kotlin/com/blucky8649/brocallie/KotlinMultiplatform.kt
- gradle/libs.versions.toml
- shared/feature/conversation/src/commonMain/kotlin/com/blucky8649/conversation/ChatScreen.kt
- shared/feature/conversation/src/commonMain/kotlin/com/blucky8649/conversation/ChatViewModel.kt
implementation datetime library to retrieve current timestamp.
> implementation datetime library

- shared/core/room/src/commonMain/kotlin/com.blucky8649.room/dao/CallieDao.kt
add insert query in callies table
> add insert query in callies table

- androidApp/build.gradle.kts
- androidApp/src/main/res/drawable/photo_ai.xml
- build-logic/convention/src/main/kotlin/com/blucky8649/brocallie/ComposeMultiplatform.kt
- gradle/libs.versions.toml
- settings.gradle.kts
- shared/build.gradle.kts
- shared/core/designsystem/src/commonMain/kotlin/com/blucky8649/designsystem/BcText.kt
- shared/core/room/src/commonMain/kotlin/com.blucky8649.room/util/InstantConverter.kt
- shared/feature/createcallie/build.gradle.kts
- shared/feature/createcallie/src/androidMain/kotlin/com/blucky8649/createcallie/CreateCallieRoute.kt
- shared/feature/createcallie/src/commonMain/composeResources/drawable/photo_ai.xml
- shared/feature/createcallie/src/commonMain/composeResources/values-ko-rKR/strings.xml
- shared/feature/createcallie/src/commonMain/composeResources/values/strings.xml
- shared/feature/createcallie/src/commonMain/kotlin/com/blucky8649/createcallie/CreateCallieScreen.kt
> Add Screen : Craete Callie

- build.gradle.kts
- gradle/libs.versions.toml
- shared/feature/createcallie/build.gradle.kts
- shared/feature/createcallie/src/commonMain/kotlin/com/blucky8649/createcallie/CreateCallieScreen.kt
- shared/feature/createcallie/src/commonMain/kotlin/com/blucky8649/createcallie/CreateCallieUiState.kt
- shared/feature/createcallie/src/commonMain/kotlin/com/blucky8649/createcallie/CreateCallieViewModel.kt
Connect the Callie create screen with the Gemini API
> Connect the Callie create screen with the Gemini API

- build.gradle.kts
- gradle.properties
- gradle/libs.versions.toml
- shared/core/room/build.gradle.kts
- shared/core/room/src/commonMain/kotlin/com.blucky8649.room/Database.kt
- shared/core/room/src/commonMain/kotlin/com.blucky8649.room/dao/MessageDao.kt
- shared/core/room/src/commonMain/kotlin/com.blucky8649.room/model/CallieEntity.kt
- shared/core/room/src/commonMain/kotlin/com.blucky8649.room/model/ChatRoomEntity.kt
- shared/core/room/src/commonMain/kotlin/com.blucky8649.room/model/MessageEntity.kt
- shared/core/room/src/iosMain/kotlin/com.blucky8649.room/Database.ios.kt
1. https://issuetracker.google.com/issues/342905180
2. https://issuetracker.google.com/issues/348166275
> Resolve build issues related to Room and Ksp

- gradle/libs.versions.toml
- iosApp/iosApp/ContentView.swift
- shared/build.gradle.kts
- shared/core/room/src/iosMain/kotlin/com.blucky8649.room/Database.ios.kt
- shared/feature/conversation/src/commonMain/kotlin/com/blucky8649/conversation/ChatScreen.kt
- shared/feature/conversation/src/iosMain/kotlin/com/blucky8649/conversation/ChatScreen.ios.kt
- shared/feature/createcallie/src/iosMain/kotlin/CreateCallieScreen.ios.kt
Modify features related iOS Platform (DB, UI)
> Modify features related iOS Platform (DB, UI)

- shared/core/designsystem/src/commonMain/kotlin/com/blucky8649/designsystem/loading/LoadingProgressView.kt
- shared/feature/conversation/src/commonMain/kotlin/com/blucky8649/conversation/ChatScreen.kt
- shared/feature/conversation/src/commonMain/kotlin/com/blucky8649/conversation/ChatViewModel.kt
- shared/feature/conversation/src/commonMain/kotlin/com/blucky8649/conversation/component/ChatBubble.kt
- shared/feature/conversation/src/commonMain/kotlin/com/blucky8649/conversation/component/TextMessage.kt
Add LoadingProgressView in Conversation Screen
> Add LoadingProgressView in Conversation Screen

- build-logic/convention/src/main/kotlin/com/blucky8649/brocallie/KotlinMultiplatform.kt
- gradle/libs.versions.toml
Implement Coroutines dependencies
> Implement Coroutines dependencies

- shared/build.gradle.kts
- shared/core/room/src/desktopMain/kotlin/com.blucky8649.room/Database.desktop.kt
- shared/core/ui/src/desktopMain/kotlin/com/blucky8649/ui/BcApp.desktop.kt
- shared/src/commonMain/kotlin/com/blucky8649/brocallie/main.kt
Initial setup for kotlin-desktop target
> Initial setup for kotlin-desktop target

- shared/core/room/src/commonMain/kotlin/com.blucky8649.room/dao/CallieDao.kt
- shared/feature/contacts/src/commonMain/composeResources/values-ko-rKR/strings.xml
- shared/feature/contacts/src/commonMain/composeResources/values/strings.xml
- shared/feature/contacts/src/commonMain/kotlin/com/blucky8649/contacts/ContactItem.kt
- shared/feature/contacts/src/commonMain/kotlin/com/blucky8649/contacts/ContactsScreen.kt
[#61] Add delete and undo feature on main screen
> [#61] Add delete and undo feature on main screen

- iosApp/iosApp.xcodeproj/project.pbxproj
- iosApp/iosApp/ContentView.swift
- iosApp/iosApp/Info.plist
- iosApp/iosApp/Push/BcNotificationDelegate.swift
- iosApp/iosApp/iOSApp.swift
- iosApp/iosApp/iosApp.entitlements
init push notifications in ios target
> init push notifications in ios target

- androidApp/src/main/java/com/blucky8649/brocallie/push/BcFcmService.kt
Add Push Image Loader in Android target
> Add Push Image Loader in Android target

- iosApp/BcNotificationService/Info.plist
- iosApp/BcNotificationService/NotificationService.swift
- iosApp/iosApp.xcodeproj/project.pbxproj
Add Notification Service Extension in iOS
> Add Notification Service Extension in iOS

- iosApp/BcNotificationService/NotificationService.swift
- iosApp/iosApp.xcodeproj/project.pbxproj
Add a notification image in iOS
> Add a notification image in iOS

- androidApp/build.gradle.kts
- androidApp/src/main/java/com/blucky8649/brocallie/android/MainActivity.kt
Update target sdk version to 35 in Android
> Update target sdk version to 35 in Android

- gradle/libs.versions.toml
Fix red screen issue when starting app
update eungabi version to 0.3.3
> Fix red screen issue when starting app
